name: PR Test for SGL-KERNEL-NPU (Ascend NPU)

on:
  pull_request:
    branches: [ main ]
    paths:
      - "build.sh"
      - "cmake/**"
      - "python/**"
      - "csrc/**"
      - "test/**"
      - ".github/workflows/pr-test-npu.yml"
  workflow_dispatch:

concurrency:
  group: pr-test-npu-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-all-build:
    if: (github.repository == 'sgl-project/sgl-kernel-npu' || github.event_name == 'pull_request') &&
        github.event.pull_request.draft == false
    runs-on: linux-aarch64-a3-16
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.2.rc1-a3-ubuntu22.04-py3.11
    steps:
      - name: Clean git config
        run: |
          CONFIG_KEY='http.https://gh-proxy.test.osinfra.cn/.extraheader'
          git config --global --unset "$CONFIG_KEY" || true

      - name: Clean workspace
        run: |
          sudo rm -rf --one-file-system "$GITHUB_WORKSPACE"/* "$GITHUB_WORKSPACE"/.* 2>/dev/null || true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Install dependencies
        run: |
          # speed up by using infra cache services
          CACHING_URL="cache-service.nginx-pypi-cache.svc.cluster.local"
          sed -Ei "s@(ports|archive).ubuntu.com@${CACHING_URL}:8081@g" /etc/apt/sources.list
          pip config set global.index-url http://${CACHING_URL}/pypi/simple
          pip config set global.trusted-host ${CACHING_URL}

          bash scripts/npu_ci_install_dependency.sh

      - name: Prepare Deepep
        run: bash scripts/prepare_deepep_in_container.sh

      - name: Run test intranode
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 2239
        run: |
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_intranode.py

      - name: Run test low latency
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 1913
        run: |
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_low_latency.py

  test-build-deepep:
    if: (github.repository == 'sgl-project/sgl-kernel-npu' || github.event_name == 'pull_request') &&
        github.event.pull_request.draft == false
    runs-on: linux-aarch64-a3-16
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.2.rc1-a3-ubuntu22.04-py3.11
    steps:
      - name: Clean git config
        run: |
          CONFIG_KEY='http.https://gh-proxy.test.osinfra.cn/.extraheader'
          git config --global --unset "$CONFIG_KEY" || true

      - name: Clean workspace
        run: |
          sudo rm -rf --one-file-system "$GITHUB_WORKSPACE"/* "$GITHUB_WORKSPACE"/.* 2>/dev/null || true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Install dependencies
        run: |
          # speed up by using infra cache services
          CACHING_URL="cache-service.nginx-pypi-cache.svc.cluster.local"
          sed -Ei "s@(ports|archive).ubuntu.com@${CACHING_URL}:8081@g" /etc/apt/sources.list
          pip config set global.index-url http://${CACHING_URL}/pypi/simple
          pip config set global.trusted-host ${CACHING_URL}

          bash scripts/npu_ci_install_dependency.sh

      - name: Prepare Deepep
        run: bash scripts/prepare_deepep_in_container.sh -a deepep

      - name: Run test intranode
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 2239
        run: |
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_intranode.py

      - name: Run test low latency
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 1913
        run: |
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_low_latency.py

  finish:
    if: always()
    needs:
      - test-all-build
      - test-build-deepep
    runs-on: ubuntu-latest
    steps:
      - name: Check all dependent job statuses
        run: |
          results=(${{ join(needs.*.result, ' ') }})
          for result in "${results[@]}"; do
            if [ "$result" = "failure" ] || [ "$result" = "cancelled" ]; then
              echo "Job failed with result: $result"
              exit 1
            fi
          done
          echo "All jobs completed successfully"
          exit 0
